### ISSUE TITLE
change topbar color when user clicks link to sign in

### ISSUE THREAD

**Issue by thatbudakguy** [WatzekDigitalInitiatives/lc-package#2]
still using the default UI color. move to white? transparent?

**Comment by thatbudakguy** [comment]
using for now:
```css
prm-user-area md-fab-toolbar.md-is-open md-fab-trigger ._md-fab-toolbar-background {
  /*"sign in" bar*/
  background-color: #333 !important;
}
```
