### ISSUE TITLE
make adv search panel transparent

### ISSUE THREAD

**Issue by thatbudakguy** [WatzekDigitalInitiatives/lc-package#21]
should be:
```css
.advanced-search-backdrop.visible {
background-color: transparent;
}

button.switch-to-simple {
color: white;
}
```
